; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
src_dir = ./
default_envs = nucleo_h743zi

[env:nucleo_h743zi]
extra_scripts  = pre:stm32cube_flag.py
platform = ststm32
board = nucleo_h743zi
framework = stm32cube
lib_ldf_mode = off
debug_tool = stlink
upload_protocol = stlink
build_flags =
        -D USE_HAL_DRIVER
        -D STM32H7
        -D STM32H743xx
        -D ARM_MATH_CM7
        -D CORE_CM7
        -D STM32_IPL
        -D STM32IPL
        -I Core/Inc
        -I Drivers/CMSIS/Device/ST/STM32H7xx/include
        -I Drivers/CMSIS/Core/DSP/Include
        -I Drivers/CMSIS/include
        -I Drivers/STM32H7xx_HAL_Driver/Inc
        -I Drivers/STM32H7xx_HAL_Driver/Inc/Legacy
        -I Middlewares/ST/AI/Inc
        -I X-CUBE-AI/App
        -I Drivers/BSP/inc
        -I Middlewares/ST/AI/Inc
        -I Middlewares/ST/ImageProcessing/Inc
        -I D:/PlatformIO/packages/toolchain-gccarmnoneeabi/arm-none-eabi/include
        -L Middlewares/ST/AI/Lib -l:NetworkRuntime810_CM7_GCC
        -Wl,-Map,output.map
        -std=gnu11
build_src_filter =
        +<Core/src>
        +<X-CUBE-AI/App>
        +<Drivers/STM32H7xx_HAL_Driver/Src/>
        +<./startup_stm32h743xx.s>
        +<Drivers/BSP/src>
        +<Middlewares/ST/ImageProcessing/Src/imlib.c>
        +<Middlewares/ST/ImageProcessing/Src/stm32ipl_convert.c>
        +<Middlewares/ST/ImageProcessing/Src/stm32ipl_image_io.c>
        +<Middlewares/ST/ImageProcessing/Src/stm32ipl_mem_alloc.c>
        +<Middlewares/ST/ImageProcessing/Src/stm32ipl_resize.c>
        +<Middlewares/ST/ImageProcessing/Src/stm32ipl.c>
        +<Middlewares/ST/ImageProcessing/Src/umm_malloc.c>
board_build.ldscript = ./STM32H743IITx_FLASH.ld
board_build.stm32cube.custom_config_header = yes
board_build.stm32cube.startup_file = ./startup_stm32h743xx.s
board_build.stm32cube.system_file = Core/Src/system_stm32h7xx.c
board_build.stm32cube.custom_dsp_library = yes